// blog/front/react_html/src/views/Detail.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom'
import { Typography } from 'antd';
import blogService from "../service/blogHttp"
class Detail extends Component {
    constructor(props) {
        super(props);
        this.state = {
            detail: null
        }
    }
    async componentDidMount() {
        let res = await blogService.getDetail({ id: this.props.match.params.id })
        if (res && res.errno === 0) {
            this.setState({
                detail: res.data
            })
        }
    }
    render() {
        const { Title, Paragraph, Text } = Typography;
        const { title, content, author } = this.state.detail ? this.state.detail : {}
        return (
            <div style={{margin:"20px"}}>
                <Title>{title}</Title><Text>作者:<Link to={`/list?author=`+author} className="author_link">{author}</Link></Text>
                <Paragraph>
                    {content}
                </Paragraph>
            </div>
        )
    }
}

export default Detail

// blog/front/vue-html/src/views/Detail.vue
<template>
  <div class="detail">
    <h1>{{detail&&detail.title}}</h1>
    <p @click="goAuthorList(detail.author)">作者：{{detail&&detail.author}}</p>
    <div>{{detail&&detail.content}}</div>

  </div>
</template>
<script>
import blogService from "@/service/blogHttp";
export default {
  name:"detail",
  data(){
    return{
      detail : null
    }
  },
  mounted() {
    this.getDetail()
  },
  methods: {
    async getDetail(){
      let detailObj = await blogService.getDetail({id:this.$route.params.id});
      if(detailObj&&detailObj.errno == 0){
        this.detail = detailObj.data
      }
    },
    async goAuthorList(author){
      this.$router.push({
        path:"/list",  // 只能是name传参
        query:{
          author
        }
      })
    }
  }
}
</script>
